services:
  php:
    build:
      context: .
      dockerfile: DockerFile
    container_name: php82
    ports:
      - "8000:80"
    volumes:
      - ./Ischool:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
    ports:
      - "3309:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql8  # Nom du service MySQL
      PMA_USER: 
      PMA_PASSWORD:  
    ports:
      - 8008:80  # Accessible à partir de ton navigateur sur localhost:8080
    depends_on:
      - db
    
